meta_product_name: "Bucket list with kids"
meta_title: "Bucket list with kids - find a holiday"
meta_description: "Curated family friendly recommendations carefully selected by professionals"
meta_image: "banner.jpg"
twitter_account: "@bucketlistwithkids" # required for Twitter Cards
