meta_product_name: "Bucket list with kids"
meta_title: "Bucket list with kids - find a holiday"
meta_description: "Curated family friendly recommendations around the world"
meta_image: "cover.png"
# twitter_account: "@bucketlistwithkids" # required for Twitter Cards
